version: '3'

services:
    phpbenchmarks_composer_update:
        container_name: phpbenchmarks_composer_update
        tty: true
        build:
            context: .
            args:
                DOCKER_UID: ${DOCKER_UID}
        environment:
            - VALIDATE_DEV=${VALIDATE_DEV}
            - REPOSITORIES_CREATED=${REPOSITORIES_CREATED}
            - RESULT_TYPE_SLUG=${RESULT_TYPE_SLUG}
        volumes:
            - ${INSTALLATION_PATH}:/var/www/phpbenchmarks
